import hashlib
import logging
import secrets
from datetime import datetime, timedelta, timezone

from fastapi import HTTPException, Request
from pymongo.errors import DuplicateKeyError

from .db import db

logger = logging.getLogger("lvlnet.auth")

# Session tokens are opaque 256-bit random hex strings stored server-side in
# `db.sessions`. The client refreshes 60s before `expiresIn`, so the stored TTL
# must be >= the advertised one — we keep them equal.
SESSION_TTL_SECONDS = 3600

# Client secrets must be high-entropy random strings generated by the mod
# (recommended: 64 hex chars = 256 bits). The floor below just rejects anything
# that obviously isn't that (short / guessable junk).
MIN_SECRET_LENGTH = 32
MAX_SECRET_LENGTH = 256


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _as_aware(dt: datetime) -> datetime:
    """Mongo round-trips datetimes as naive UTC; normalize for comparison."""
    return dt if dt.tzinfo is not None else dt.replace(tzinfo=timezone.utc)


def _hash_secret(secret: str) -> str:
    """SHA-256 of the client secret. The secret is itself 256 bits of client-
    generated randomness (not a human password), so a fast unsalted hash is
    appropriate — there is nothing to dictionary-attack. We store only the
    digest so a database leak doesn't leak usable credentials."""
    return hashlib.sha256(secret.encode("utf-8")).hexdigest()


async def register_or_verify_secret(gsid: str, secret: str) -> bool:
    """Trust-on-first-use credential check.

    First login for a gsid: store the secret's hash and claim the identity.
    Every later login: the presented secret must hash to the stored value.

    Returns True if this call REGISTERED the identity (first use), False if it
    verified an existing one. Raises 401 on mismatch. Safe under concurrent
    first logins: the unique index on gsid makes exactly one insert win, and
    the loser falls through to verification against the winner's hash."""
    if len(secret) < MIN_SECRET_LENGTH or len(secret) > MAX_SECRET_LENGTH:
        raise HTTPException(
            400,
            f"secret must be between {MIN_SECRET_LENGTH} and "
            f"{MAX_SECRET_LENGTH} characters",
        )

    digest = _hash_secret(secret)
    existing = await db.client_secrets.find_one({"gsid": gsid})

    if existing is None:
        try:
            await db.client_secrets.insert_one(
                {
                    "gsid": gsid,
                    "secret_hash": digest,
                    "created_at": _utcnow(),
                }
            )
            logger.info("registered new identity for gsid %s", gsid)
            return True
        except DuplicateKeyError:
            # Lost a race with a concurrent first login — verify instead.
            existing = await db.client_secrets.find_one({"gsid": gsid})
            if existing is None:  # pathological; treat as auth failure
                raise HTTPException(401, "Invalid credentials")

    if not secrets.compare_digest(existing["secret_hash"], digest):
        logger.warning("secret mismatch for gsid %s", gsid)
        raise HTTPException(401, "Invalid credentials")
    return False


async def create_session(gsid: str, client_version: str = "") -> str:
    """Mint an opaque session token bound to `gsid` with a 1h TTL."""
    token = secrets.token_hex(32)  # 256 bits
    now = _utcnow()
    await db.sessions.insert_one(
        {
            "token": token,
            "gsid": gsid,
            "client_version": client_version or "",
            "created_at": now,
            "expires_at": now + timedelta(seconds=SESSION_TTL_SECONDS),
        }
    )
    return token


async def require_session(request: Request) -> str:
    """FastAPI dependency: resolve `Authorization: Bearer <token>` to a gsid.

    Missing / unknown / expired token -> 401. The client invalidates its cached
    token on 401, re-authenticates exactly once, and retries the request, so
    enforcing expiry here is safe."""
    header = request.headers.get("Authorization", "")
    scheme, _, token = header.partition(" ")
    token = token.strip()
    if scheme.lower() != "bearer" or not token:
        raise HTTPException(401, "Missing bearer token")

    session = await db.sessions.find_one({"token": token})
    if not session:
        raise HTTPException(401, "Invalid or expired session token")
    if _as_aware(session["expires_at"]) <= _utcnow():
        # Best-effort cleanup; the TTL index will catch anything we miss.
        await db.sessions.delete_one({"_id": session["_id"]})
        raise HTTPException(401, "Invalid or expired session token")

    return session["gsid"]


def enforce_gsid(token_gsid: str, supplied_gsid: str | None) -> str:
    """The token's gsid is authoritative. A supplied form/query gsid that
    disagrees with it is rejected with 401 and logged; an absent one is fine.
    Returns the authoritative gsid."""
    supplied = (supplied_gsid or "").strip()
    if supplied and supplied != token_gsid:
        logger.warning(
            "gsid mismatch: token gsid %s, supplied gsid %s", token_gsid, supplied
        )
        raise HTTPException(401, "gsid does not match the session token")
    return token_gsid